version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${APP_PORT}:6379
    networks:
      - default
    volumes:
      - /root/redis/data:/db
    command:
      - --requirepass ${APP_PASS}

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:${APP_PORT}
    ports:
    - ${COMMANDER_PORT}:8081

networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local
  data:
    driver: local
